version: '3.3'

services:
  aospace:
    privileged: true
    image: localhost/aospace-all-in-one:v1.0.0
    container_name: aospace-all-in-one
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
      - "127.0.0.1:2001:2001"
      - "127.0.0.1:8080:8080"
      - "12841:80"
      - "18569:443"
      - "127.0.0.1:3001:3001"
      - "5678:5678"
      - "127.0.0.1:5680:5680"
    environment:
      DATADIR: /home/debian/aospace
      POSTGRES_PASSWORD: placeholder_mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_FILEDB: file
      POSTGRES_MAILDB: mail
      POSTGRES_GATEWAYDB: gateway
      POSTGRES_ACCOUNTDB: account
      PGDATA: /data
      REDIS_HOST: aospace-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "placeholder_mysecretpassword"
      BUCKET_SOURCE: "eulixspace-files"
      BUCKET_TARGET: "eulixspace-files-processed"
      ROOT_DATA_DIR: "/data/"
      LIBREOFFICE_PROCESS_TIMEOUT: 900
      DEBUG_MODE: 1
      SQL_DATABASE: file
      SQL_HOST: aospace-postgresql
      SQL_PORT: 5432
      SQL_USER: postgres
      SQL_PASSWORD: placeholder_mysecretpassword
      REDIS_URL: aospace-redis:6379
      REDIS_PASS: placeholder_mysecretpassword
      DATA_PATH: /data/
      NOTIFY_AMQP_URL: "amqp://root:mysecretpassword@localhost:5672"
      NOTIFY_QUEUE_NAME: fileChangelogs
      NOTIFY_AMQP_ENABLE: "on"
      HEAD_IMAGE_PATH: /headimage/
      PUBLIC_SHARED_INFO_FILE: shared_info.json
      GIN_MODE: release
      SENTRY_DSN: https://99fb77b329b64e10833741dc4835a94f@sentry.eulix.xyz/14
      SENTRY_RELEASE: eulixspace-fileapi@1.0.3
      SENTRY_ENVIRONMENT: release
      DISK_INFO_FILE_NAME: "disk_info.json"
      DISK_PART_FOLDER_PREFIX: "ao_part_"
      APP_BOX_DEPLOY_METHOD: DockerBox
      ACCOUNT_URL: http://localhost:8080
      RADICALE: http://root:root@localhost:5232/root/
      APP_BOX_PUBLIC_KEY_LOCATION: /etc/ao-space/box_key_pub.pem
      APP_BOX_PRIVATE_KEY_LOCATION: /etc/ao-space/box_key.pem
      APP_CLIENT_PUBLIC_KEY_LOCATION: /etc/ao-space/client_key_pub.pem
      APP_GATEWAY_FILE_SYSTEM_LOCATION: /eulixspace-data/symlink/
      APP_SHARED_INFO_FILE: /data/shared/shared_info.json
      APP_ACCOUNT_IMAGE_LOCATION: /opt/eulixspace/image/
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: placeholder_mysecretpassword
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://localhost:5432/account
      QUARKUS_REDIS_HOSTS: redis://localhost:6379
      QUARKUS_REDIS_PASSWORD: placeholder_mysecretpassword
      APP_FILEAPI_URL: http://localhost:2001/space/v1/api
      APP_ACCOUNT_DATA_LOCATION: /opt/eulixspace/data/
      MAX_INVITE_MEMBER_COUNT: 9
      APP_INTERNET_SERVICE_CONFIG: /etc/ao-space/internet_service_config.json
      APP_RUN_NETWORK_MODE: bridge
      AOSPACE_DATADIR: ${DATADIR}
      RUN_NETWORK_MODE: host
    volumes:
      - /home/eulixspace_link/postgresql/data:/data/postgresql
      - /home/eulixspace_link/redis/data:/data/redis
      - /home/eulixspace_file_storage/parts:/data/storage
      - /opt/eulixspace/image:/headimage
      - /etc/ao-space/meta/shared:/shared
      - /home/eulixspace_file_storage/parts/ao_part_dummy/dav/cards/collections/collection-root/root:/addressbook
      - /opt/eulix:/opt/eulix
      - /etc/ao-space:/etc/ao-space
      - /home/eulixspace_file_storage/parts/ao_part_dummy/eulixspace-files:/eulixspace-data
      - /etc/ao-space/meta/shared:/data/shared
      - /opt/logs/gateway:/logs
      - /opt/eulixspace/image:/opt/eulixspace/image
      - /opt/eulixspace/applet:/opt/eulixspace/applet
      - /etc/ao-space/meta/admin:/opt/eulixspace/data
      - /opt/eulixspace-web/space/applet/:/opt/eulixspace-web/space/applet/
      - /home/eulixspace_link/nginx/conf.d:/etc/nginx/conf.d
      - /etc/ao-space/certs:/etc/nginx/certs
      - /home/eulixspace_file_storage/parts:/home/eulixspace/data
      - ${DATADIR}/aospace
      - /var/run/docker.sock:/var/run/docker.sock:ro
  aonetwork-client:
    container_name: aonetwork-client
    image: ghcr.io/ao-space/gt:client-v2.2.3
    restart: always
    volumes:
      - /etc/ao-space/gt:/opt/config

networks:
  default:
    external:
      name: ao-space
